name: SizePlayer
version: 1.0.0
main: SizePLayer\SizePLayer
api: [3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15]

commands:
    size:
        description: Change your player size !
        permission: size.permission
        usage: /size [New Size]
    

permission:
  size.permission: 
    default: op
